### PR TITLE
added yuan.svg

### PR DESCRIPTION
**Pull request by zeelsheladiya**

### CODE REVIEW

**Comment by zeelsheladiya** [comment]
sorry because I messed up a little bit. this is my first time contributing to an open-source project, so apologize. 
Now, I tried to do as you said, can check my request now.

**Comment by Klarr-Agency** [comment]
No worries, looks good now!

Like I said in the previous PR, our designer will review it tomorrow.

I really appreciate the time that you put on our project.

Have a nice day! 🎉

**Comment by zeelsheladiya** [comment]
I am also working on other icons. As soon as you approved my icons i will add more and more. Thank you. Open-source is really fun. Thank you so much for your project.

**Comment by Roxanne-B** [comment]
Hi, I'm the designer! 

Last Friday, I looked at the icon you submitted and today, I did a small correction guide. The icon corresponds well with our graphic style. However, there are some technical errors. If you have any questions, feel free to write to me and thank you for your contribution ☺️

Btw, may I know which software you use?

[Yuan_Corrections.zip](https://github.com/Klarr-Agency/Circum-Icons/files/9954097/Yuan_Corrections.zip)

**Comment by zeelsheladiya** [comment]
I used illustrator for that. I will go through your changes and I will make sure to correspond with your icon style. Thank you.

**Comment by Klarr-Agency** [comment]
Hi @zeelsheladiya,

Are you alright with the correction?

**Comment by zeelsheladiya** [comment]
Yes. I got it. Thanks fir the correction. I am working on the icon. In addition i am having exams right now so upload might take weeks.🥲

**Comment by Klarr-Agency** [comment]
Alright, no problem, good luck with your exams! 😃

**Pull request closed without merging**
